import {assets} from './assets.js';
import {content} from './content.js';

const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paras=t=>t.trim().split(/\n\s*\n/).map(p=>`<p>${esc(p.trim())}</p>`).join('');
const A=i=>assets.find(a=>a.i===i);
const sourceLinks={vac:'https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020',vimy:'https://www.veterans.gc.ca/en/remembrance/military-history/first-world-war/battle-vimy-ridge',museum:'https://www.warmuseum.ca/articles/the-battle-of-vimy-ridge-april-9-to-12-1917',bio:'https://thecanadianencyclopedia.ca/en/article/henry-norwest',cbc:'https://www.cbc.ca/news/canada/edmonton/henry-norwest-metis-marksman-1.4044782',poem:'https://en.wikisource.org/wiki/A_Highland_Regiment/On_Vimy_Ridge',scott:'https://www.gutenberg.org/files/46427/46427-h/46427-h.htm#Page_102'};
const ext=(url,label,cls='')=>`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener">${label}</a>`;
const imageButton=(i,extra='')=>{const a=A(i);return `<button class="image-button ${a.sensitive?'sensitive-thumb':''} ${extra}" data-image="${i}" aria-label="${a.sensitive?'View historical image with content notice: ':'Enlarge: '}${esc(a.title)}"><img src="${a.src}" alt="${a.sensitive?'Historical battlefield image, concealed until opened':esc(a.title)}" loading="lazy" width="${a.width}" height="${a.height}">${a.sensitive?'<span class="sensitive-label">Historical image<br>Contains dead soldiers<br>Click to view</span>':''}<span class="expand" aria-hidden="true">+</span></button>`};
const figure=(i,cls='',showCaption=true)=>{const a=A(i);return `<figure class="figure ${cls}">${imageButton(i)}${showCaption?`<figcaption><strong>${esc(a.title)}</strong>${esc(a.caption)}</figcaption>`:''}</figure>`};
const gallery=(ids,cls='',showCaption=true)=>`<div class="gallery-grid ${cls}">${ids.map(i=>figure(i,'',showCaption)).join('')}</div>`;
const eventMedia=m=>{if(m.asset!=null)return imageButton(m.asset);const src=m.page?`assets/records/page-${String(m.page).padStart(2,'0')}.webp`:m.file;return `<button class="event-media-button ${m.rotation?'rotated':''}" data-event-media="${esc(src)}" data-event-label="${esc(m.label)}" data-event-rotation="${m.rotation||0}" aria-label="Enlarge ${esc(m.label)}"><img src="${esc(src)}" alt="${esc(m.label)}" loading="lazy"><span class="expand" aria-hidden="true">+</span></button>`};
const next=(route,label)=>`<div class="wrap"><a class="next-chapter" href="#${route}"><div><span class="eyebrow red">CONTINUE THE STORY</span><h3>${label}</h3></div></a></div>`;
const top=(num,label,title,description,links=[])=>`<div class="wrap"><header class="page-top"><div class="breadcrumbs"><a href="#home">The exhibition</a> &nbsp;/&nbsp; ${label}</div><span class="eyebrow red"><span class="chapter-num">${num}</span>${label}</span><h1>${title}</h1><p class="lead">${description}</p>${links.length?`<nav class="subnav" aria-label="In this chapter">${links.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}</nav>`:''}</header></div>`;
const sourceLine=(label='Project research and original records',url='#sources')=>`<p class="source-line">Sources: <a href="${url}">${label}</a></p>`;

function home(){return `<section class="hero"><div class="hero-copy"><h1>The life of<br><em>Henry Norwest.</em></h1><p class="lead">Learn more about the life of Henry Norwest and the battles he fought in.</p><div class="button-row"><a href="#life" class="button primary">Discover his story</a><a href="#timeline" class="button">Explore the timeline</a></div></div><div class="hero-art"><img class="hero-record" src="assets/asset-36.webp" alt="Norwest’s signed attestation paper, 1915"><div class="portrait-frame"><img src="assets/asset-35.webp" alt="Portrait of Henry Norwest in uniform in 1915" fetchpriority="high"></div><div class="hero-tag"><small>SERVICE RECORD · CANADA</small><strong>Henry Louis<br>Norwest</strong><div class="line"></div><p>NO. 435684<br>50TH CANADIAN INFANTRY BATTALION</p></div><div class="hero-years">1884 — 1918</div></div></section>
<div class="fact-strip"><div><small>His hometown</small><strong>Fort Saskatchewan, Alberta</strong></div><div><small>His identity</small><strong>Métis · French-Cree ancestry</strong></div><div><small>His service</small><strong>Canadian Expeditionary Force</strong></div><div><small>His honours</small><strong>Military Medal & Bar</strong></div></div>
<section class="section wrap"><div class="section-header"><div><span class="eyebrow red">EXPLORE THE EXHIBITION</span><h2>His life and records.</h2></div></div><div class="chapter-grid">${[['life',34,'01','Before the uniform'],['timeline',36,'03','A life, year by year'],['vimy',17,'04','On Vimy Ridge']].map(([r,i,n,t])=>`<a href="#${r}" class="chapter-card"><div class="chapter-image"><img src="${A(i).src}" alt="${esc(A(i).title)}" loading="lazy"><span class="chapter-number">${n}</span></div><h3>${t}</h3><span class="text-link">Explore chapter</span></a>`).join('')}</div><div class="chapter-directory"><span class="eyebrow red">EVERY CHAPTER, AT A GLANCE</span><div>${[['service','02','Military service'],['poetry','05','Art & poetry'],['remembrance','06','Remembrance'],['reflections','07','Personal reflections'],['archive','08','The complete archive'],['sources','09','Works Cited']].map(([r,n,t])=>`<a href="#${r}"><small>${n}</small><span>${t}</span></a>`).join('')}</div></div></section>
<section class="home-archive"><div class="document-collage" aria-hidden="true"><img src="assets/records/page-01.webp" alt="" loading="lazy"><img src="assets/records/page-03.webp" alt="" loading="lazy"></div><div class="home-archive-copy"><span class="eyebrow">IN HIS RECORDS</span><h2>The Original<br>Documents.</h2><p>Open the enlistment papers. Read the battalion’s words. Explore all 66 pages of Norwest’s personnel file, alongside every photograph and document in this collection.</p><div class="button-row"><button class="button light" data-record="1">Open the service file</button><a href="#archive" class="button light">Visit the archive</a></div></div></section>
<section class="home-closing"><h2>“We have lost his services but his memory will be ever with us, his example an inspiration.”</h2><p>From the commanding officer’s tribute · 18 August 1918</p><div class="button-row" style="justify-content:center"><button class="text-link" data-image="31">Read the original tribute</button></div></section>`}

function life(){return `${top('01','His life','Life before the <em>War.</em>','Before he became a soldier, Henry Norwest had a home, a family, and a life in Alberta.')}
<section class="section wrap"><div class="two-col"><article class="profile"><div class="profile-head"><img src="assets/asset-35.webp" alt="Henry Norwest, 1915"><div><h2>Henry Louis<br>Norwest</h2><span class="eyebrow">ALSO KNOWN AS “DUCKY”</span></div></div><dl>${[['Born','8 May 1884¹'],['Birthplace','Fort Saskatchewan, now Alberta, Canada'],['Identity','Métis, of French-Cree ancestry'],['Parents','Louis and Genevieve Norwest'],['Family','Widowed; father of three children'],['Home','Bashaw, Alberta'],['Before the war','Ranch hand and rodeo performer'],['Religion','Roman Catholic'],['Died','18 August 1918, near Fouquescourt, France'],['Burial','Warvillers Churchyard Extension · A.30']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><div class="note"><strong>¹ A small difference in the records</strong>Veterans Affairs Canada gives 8 May 1884. The September attestation paper records 1 May 1884.</div></article><div><div class="prose"><span class="eyebrow">A LIFE IN ALBERTA</span><p>Henry Louis Norwest was Métis, of French-Cree ancestry. Before the First World War, he worked as a ranch hand and rodeo performer. His pre-war photograph shows him working as a rodeo performer.</p><p>Henry Norwest had a family, community, and work before he joined the war. This helps us remember that he wasn’t just a soldier but had a family and home before the war.</p></div>${figure(34)}<div class="note"><details><summary>Reading his family records</summary><p>The September 1915 attestation marks him as married, while family accounts say his wife died before his wartime service. He was the father of three children.</p></details></div>${sourceLine('Veterans Affairs Canada; family newspaper feature; attestation paper')}</div></div></section>
<section class="section full-bleed"><div class="wrap two-col wide-text"><div class="prose"><span class="eyebrow">THE DOCUMENT THAT OPENS THE STORY</span><h2>His Enlistment<br>in the War.</h2><p>On 8 September 1915, Henry Norwest enlisted in Calgary. The attestation paper records his father, Louis Norwest, as his next of kin and his earlier service with the Royal North-West Mounted Police. His signature appears beneath the declaration and oath.</p><p>This was his second enlistment. Earlier that year, he had joined the 3rd Canadian Mounted Rifles under the name Henry Louie. After being discharged for drunkenness and misconduct, he enlisted again as Henry Norwest and joined the 50th Battalion.</p><div class="button-row"><button class="button primary" data-image="36">Examine the attestation</button><button class="button" data-record="1">Compare both enlistments</button></div></div>${figure(36,'contain')}</div></section>${next('service','The soldier he became')}`}

function service(){return `${top('02','Military service','His Life in<br><em>the War.</em>','His military records tell us about the battles he fought in, his injuries, and his achievements.')}
<section class="section wrap" style="padding-top:35px"><span class="eyebrow red">A SUMMARY OF HIS MILITARY INFORMATION</span><div class="service-grid">${[['Service number','435684'],['Battalion','50th Battalion'],['Unit / regiment','Canadian Infantry<br>(Alberta Regiment)'],['Highest rank in accounts','Lance Corporal'],['Frontlines fought','Europe · Western Front'],['Honours','Military Medal & Bar']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><p class="source-line">Rank note: the Veterans Affairs memorial lists Private, while its biography and other records describe him as a lance corporal.</p></section>
<section class="section wrap" style="padding-top:10px"><div class="two-col wide-text"><div class="prose"><span class="eyebrow">THE WORK OF A SNIPER</span><h2>His experience<br>as a sniper.</h2><p>Henry Norwest’s earlier work as a rodeo performer and ranch hand helped him develop observation, patience, and concentration, skills that mattered as a sniper. He worked in dangerous ground between the opposing lines to protect Canadian soldiers.</p><p>The 50th Battalion war diary describes his methods and ability to remain concealed. His commanding officer’s tribute also remembers his remarkable patience and focus.</p><p>Accounts record 115 fatal shots confirmed by an observer. His total may have been higher, because a hit was counted only when an observer could confirm it.</p>${sourceLine('Veterans Affairs Canada; 50th Battalion diary and tribute')}</div><div>${figure(29)}</div></div></section>
<section class="section dark-section"><div class="wrap"><span class="eyebrow">RECOGNITION FOR BRAVERY</span><div class="two-col" style="margin-top:20px"><div><h2>His Medals<br>and Achievements.</h2><div class="medal-story"><img class="medal-photo" src="assets/military-medal.jpg" alt="An example of the Military Medal, not Norwest’s own medal"><div><h3>Military Medal & Bar</h3><p>The medal recognized bravery in the field. A bar marked a further award of the same medal.</p><p class="medal-provenance">Example medal, not Norwest’s own.</p></div></div></div><div class="prose"><p>Norwest earned the Military Medal for his actions after the capture of the Pimple at Vimy Ridge in April 1917. By targeting enemy snipers, he helped protect other Canadian soldiers.</p><p>In 1918, he was also awarded a bar to the medal. Veterans Affairs Canada places him among roughly 830 members of the Canadian Expeditionary Force who received this double honour.</p><p>Henry Norwest’s name is also listed in the First World War Book of Remembrance. His commanding officer wrote a tribute after his death.</p><div class="button-row"><button class="button light" data-image="31">Read the commander’s tribute</button></div>${sourceLine('Canadian Virtual War Memorial',sourceLinks.vac)}</div></div></div></section>
<section class="section wrap"><div class="section-header"><div><span class="eyebrow red">EVIDENCE OF SERVICE</span><h2>Original Documents.</h2></div><p>The commanding officer wrote this tribute about Norwest; the battalion diary records his unit’s service.</p></div>${gallery([28,27,31],'documents')}</section>
<section class="section full-bleed"><div class="wrap two-col"><div class="prose"><span class="eyebrow">LIFE AT THE FRONT</span><h2>Life in the War.</h2><p>His wartime experience included trench warfare, artillery fire, exhaustion, and the constant danger of enemy attacks. Henry Norwest served in the Battle of the Somme, the Battle of Vimy Ridge, and the Battle of Amiens.</p><p>The personnel file records medical treatment, including a knee injury and an accidental wound to his right foot. It also contains pay records and disciplinary paperwork.</p><div class="button-row"><button class="button primary" data-record-medical="1">Open medical records</button><a href="#timeline" class="button">View a timeline of his life</a></div></div>${figure(19)}</div></section>${next('timeline','A life, year by year')}`}

let year='All',eventIndex=0;
function timeline(){return `${top('03','Interactive timeline','The life of<br><em>Henry Norwest.</em>','A timeline of his whole life. Select a year, then choose an event to read its story and view the related evidence.')}<div class="wrap"><div class="year-tabs" role="group" aria-label="Filter timeline by year">${['All','1884','1915','1916','1917','1918'].map(y=>`<button data-year="${y}" aria-pressed="${year===y}">${y==='All'?'All years':y}</button>`).join('')}</div><div class="timeline-intro"><span>Choose a moment to look closer. On a phone, swipe across the event cards.</span></div><div class="timeline-layout"><div class="timeline-list" aria-label="Life events">${content.timeline.map((e,i)=>`<button class="event-button" data-event="${i}" aria-pressed="${i===eventIndex}" ${year!=='All'&&year!==e.year?'hidden':''}><small>${esc(e.date)}</small><strong>${esc(e.title)}</strong></button>`).join('')}</div><article id="event-detail" class="event-detail" aria-live="polite">${eventDetail()}</article></div></div>${next('vimy','The Battle of Vimy Ridge')}`}
function eventDetail(){const e=content.timeline[eventIndex];const visible=content.timeline.map((x,i)=>i).filter(i=>year==='All'||content.timeline[i].year===year);const pos=visible.indexOf(eventIndex);const media=e.media|| (e.asset!=null?[{asset:e.asset}]:[]);return `<span class="eyebrow red">${esc(e.kind)} · MOMENT ${String(eventIndex+1).padStart(2,'0')}</span><h2>${esc(e.title)}</h2><div class="event-year">${esc(e.date)}</div><p>${esc(e.text)}</p>${media.length?`<div class="event-media-grid">${media.map(m=>`<div>${eventMedia(m)}${m.label&&m.showCaption!==false?`<small>${esc(m.label)}</small>`:''}</div>`).join('')}</div>`:''}<div class="event-nav"><button class="icon-button" data-event-step="-1" aria-label="Previous event" ${pos<=0?'disabled':''}>Previous</button><span>${pos+1} / ${visible.length} ${year==='All'?'events':`events in ${year}`}</span><button class="icon-button" data-event-step="1" aria-label="Next event" ${pos===visible.length-1?'disabled':''}>Next</button></div>`}

function fitRotated(img,container,degrees){if(!degrees||!img.naturalWidth)return;const width=container.clientWidth-16,height=container.clientHeight-16;const side=degrees%180!==0;const scale=Math.min(width/(side?img.naturalHeight:img.naturalWidth),height/(side?img.naturalWidth:img.naturalHeight));img.style.width=`${img.naturalWidth*scale}px`;img.style.height=`${img.naturalHeight*scale}px`;img.style.transform=`translate(-50%,-50%) rotate(${degrees}deg)`}
function prepareEventMedia(){document.querySelectorAll('.event-media-button.rotated').forEach(button=>{const img=button.querySelector('img');const angle=+button.dataset.eventRotation;if(!img.dataset.rotationReady){img.addEventListener('load',()=>fitRotated(img,button,angle));img.dataset.rotationReady='1'}if(img.complete)fitRotated(img,button,angle)})}

function vimy(){return `${top('04','The Battle of Vimy Ridge','Understanding the<br><em>Battle of Vimy Ridge.</em>','9–12 April 1917 in northern France. All four Canadian divisions fought together in a battle often remembered as one of Canada’s greatest military victories.',['vimy/overview','vimy/map','vimy/conditions','vimy/aftermath'].map((x,i)=>[x,['The battle','Explore the map','Life at the front','Aftermath'][i]]))}
<div class="wrap"><div class="battle-banner"><img src="assets/asset-02.webp" alt="Richard Jack’s painting of the taking of Vimy Ridge" loading="eager"><div class="banner-caption">THE TAKING OF VIMY RIDGE, EASTER MONDAY 1917 · PAINTING</div></div><div class="battle-facts"><div><span class="eyebrow">Where</span><strong>Vimy, France</strong></div><div><span class="eyebrow">When</span><strong>9–12 April 1917</strong></div><div><span class="eyebrow">Canadian formation</span><strong>All four divisions</strong></div><div><span class="eyebrow">Wider offensive</span><strong>Battle of Arras</strong></div></div></div>
<section class="section wrap" id="overview"><div class="two-col"><div class="prose"><span class="eyebrow">WHY THIS RIDGE?</span><h2>The importance<br>of the high ground.</h2><p>Vimy Ridge was German-held high ground in Pas-de-Calais, northern France. Its height gave defenders a commanding view over the surrounding area and made it a powerful defensive position.</p><p>The Canadians were ordered to capture the ridge on the northern flank of the British attack at Arras. The operation formed part of a wider Allied offensive and was intended to support the French effort by drawing German resources away.</p><p>Capturing it would give the Allies a vantage point over enemy positions to the east. Its importance came from the landscape as well as the defences built into it.</p></div><div class="prose"><span class="eyebrow">HOW THE ATTACK UNFOLDED</span><h2>The Preparation<br>and the Attack.</h2><p>Canadian soldiers prepared for the attack by training for their objectives. Artillery helped them advance.</p><p>At 5:30 a.m. on 9 April 1917, Canadian soldiers began their attack behind a moving artillery barrage. They captured most of the ridge on the first day, Hill 145 on 10 April, and the Pimple on 12 April.</p><p>Norwest served as a sniper. His actions after the capture of the Pimple helped protect Canadian troops from enemy fire and were later recognized with the Military Medal.</p></div></div><div class="battle-days">${[['09','The assault begins','The Canadian Corps advances at 5:30 a.m. Most of the ridge is captured on the first day.'],['10','Hill 145','The highest point is secured. The memorial now stands on this height.'],['12','The Pimple','The remaining northern height is captured, completing the battle for the ridge.']].map(([d,t,p])=>`<div class="day-card"><span class="eyebrow">APRIL 1917</span><br><b>${d}</b><h3>${t}</h3><p>${p}</p></div>`).join('')}</div>${sourceLine('Veterans Affairs Canada; Canadian War Museum; project research')}</section>
<section class="section full-bleed" id="map"><div class="wrap"><div class="section-header"><div><h2>The map of the<br>Battle of Vimy Ridge.</h2></div><p>Open the battle-site map to look closely at the positions and the four-day attack.</p></div><div class="map-feature">${figure(37,'',false)}</div><details class="context-map"><summary>Place Vimy on the wider Western Front</summary><div style="max-width:620px;margin:25px auto">${figure(16,'contain',false)}</div></details></div></section>
<section class="section wrap"><div class="two-col wide-text"><div class="prose"><span class="eyebrow">A MOMENT WITHIN THE BATTLE</span><h2>A highlight story<br>from the Battle.</h2><p>Captain Thain Wendell MacDowell and two runners became separated from the rest of their unit. They continued forward and entered a large German dugout, where they encountered a much larger group of soldiers.</p><p>MacDowell convinced the defenders to surrender. The account records the capture of two officers and 75 soldiers. His actions helped his battalion achieve its objective at Hill 145.</p>${sourceLine('Battle research and bibliography')}</div>${figure(17,'',false)}</div></section>
<section class="section full-bleed" id="conditions"><div class="wrap"><div class="section-header"><div><span class="eyebrow red">THE HUMAN EXPERIENCE</span><h2>Between the battles,<br>life went on.</h2></div><p>Mud, flooded tents, cramped trenches, and the work of burying the dead. These photographs bring daily conditions into view.</p></div>${gallery([7,6,5,4,3])}</div></section>
<section class="section wrap"><div class="section-header"><div><h2>Photographs of the battle.</h2></div></div>${gallery([18,19,20],'three')}</section>
<section class="section dark-section"><div class="wrap two-col"><div><span class="eyebrow">THE COST OF VICTORY</span><h2 style="margin-top:15px">Casualties in<br>the Battle.</h2><div class="cost-grid"><div><strong>10,602</strong><small>Canadian casualties</small></div><div><strong>3,598</strong><small>Canadians killed</small></div></div></div><div class="prose"><p>The capture of Vimy Ridge was a major military achievement. It also brought devastating losses.</p><p>All four Canadian divisions fought together, making Vimy an important part of the way Canadians remember the war. Its significance should include both the achievement and the suffering.</p><div class="button-row"><a href="#reflections" class="button light">Read the reflections</a></div>${sourceLine('Project research; Canadian War Museum; Veterans Affairs Canada')}</div></div></section>
<section class="section wrap" id="aftermath"><div class="section-header"><div><span class="eyebrow red">WHAT WAS LEFT BEHIND</span><h2>Aftermath of the Battle.</h2></div><p>The supplied before-and-after views show how war changed the built landscape.</p></div><div class="comparison-toolbar"><p class="marginal">Choose a pair to compare.</p><div class="segmented" role="group" aria-label="Village comparison"><button data-compare="1" aria-pressed="true">Village view 01</button><button data-compare="2" aria-pressed="false">Village view 02</button></div></div><div id="comparison">${comparison(1)}</div><div class="prose" style="max-width:800px;margin:30px 0"><p>When inhabitants returned to Vimy in 1919, they found their village devastated. The aftermath was visible in ruined streets and buildings as well as in the lives of the people who returned. Rebuilding continued after the fighting had ended.</p></div>${gallery([12,11],'two',false)}</section>
<section class="section full-bleed"><div class="wrap"><div class="section-header"><div><span class="eyebrow red">READING THE NEWS</span><h2>How victory was reported.</h2></div><p>Newspaper headlines show how the battle was reported at the time in Canada. They focused on the glory of victory and gave less attention to the number of people who died.</p></div>${gallery([23,22],'two documents',false)}</div></section>
<section class="section wrap"><div class="section-header"><div><span class="eyebrow red">VIMY TODAY</span><h2>A landscape of remembrance.</h2></div><p>The memorial, battle cemetery, and preserved battlefield can be seen in the images below.</p></div>${gallery([15,14,1,0],'four',false)}</section>${next('poetry','Art, poetry, and the memory of war')}`}
function comparison(n){return `<div class="compare-grid">${(n===1?[13,10]:[9,8]).map((i,j)=>`<div class="compare-item">${imageButton(i)}<div class="compare-label">${j===0?'Before the war':'After the destruction'} · view ${String(n).padStart(2,'0')}</div></div>`).join('')}</div>`}

function poetry(){return `${top('05','Art & poetry','Art and Poetry<br><em>of Vimy Ridge.</em>','Below are a painting and a poem about the Battle of Vimy Ridge. They help us understand the horror of the battle, how soldiers felt, and why we remember them.')}
<section class="section wrap"><div class="art-story">${figure(2,'',false)}<div class="prose"><span class="eyebrow">CANADIAN WAR ART</span><h2>The Taking<br>of Vimy Ridge.</h2><p>Richard Jack’s <em>The Taking of Vimy Ridge, Easter Monday 1917</em> shows the battlefield and wounded soldiers.</p><p>The painting helps us understand the horrors of the battle and what the soldiers experienced.</p><button class="text-link" data-image="2">Look closer at the painting</button></div></div></section>
<section class="section full-bleed"><div class="wrap"><div class="section-header"><div><h2>A poem about<br>the battle.</h2></div></div><div class="poetry-layout single-poem"><article class="poem-card"><header class="poem-header"><h3>On Vimy Ridge</h3><p>Ewart Alan Mackintosh · Scottish soldier-poet<br><em>A Highland Regiment and Other Poems</em>, 1917</p></header><div class="poem">${esc(content.poem.replace(/^On Vimy Ridge by Ewart Alan Mackintosh \(1917\n/,''))}</div><p class="source-line">Mackintosh, Ewart Alan. “On Vimy Ridge.” <em>A Highland Regiment and Other Poems</em>, John Lane, 1917, p. 48. ${ext(sourceLinks.poem,'Read the original poem')}</p></article></div></div></section>${next('remembrance','The life remembered after the war')}`}

function remembrance(){return `${top('06','Remembrance','Remembering<br><em>Henry Norwest.</em>','Henry Norwest was killed on 18 August 1918. His grave, the words of his comrades, and the memories of his family help us remember him.')}
<section class="section wrap"><div class="remembrance-hero"><div class="prose"><span class="eyebrow">18 AUGUST 1918 · FRANCE</span><h2>The death of<br>Henry Norwest.</h2><p>Near Fouquescourt, Norwest was killed by a German sniper while working with his spotter, Oliver Payne. He was 34 years old.</p><p>His commanding officer wrote a tribute on the day of his death, describing his patience, focus, and the loss to the 50th Battalion. The tribute shows how he was remembered by someone who had seen him at work.</p><div class="remembrance-location"><span class="eyebrow">HIS BURIAL PLACE</span><h3>Warvillers Churchyard Extension</h3><span>Warvillers, France · Grave A.30</span></div>${sourceLine('Veterans Affairs Canada; commanding officer’s tribute')}</div><div class="grave-pair">${figure(33)}${figure(32,'',false)}</div></div></section>
<section class="section dark-section"><div class="wrap"><span class="eyebrow">A COMMANDING OFFICER’S REMEMBRANCE</span><blockquote class="quote-block" style="margin-top:25px">“We have lost his services but his memory will be ever with us, his example an inspiration.”<cite>Commanding officer, 50th Canadian Battalion · 18 August 1918</cite></blockquote><div class="button-row"><button class="button light" data-image="31">Read the complete tribute</button></div></div></section>
<section class="section wrap"><div class="section-header"><div><span class="eyebrow red">THE RECORDS OF REMEMBRANCE</span><h2>Records that honor<br>Henry Norwest.</h2></div><p>The grave registration, inscription record, and Book of Remembrance all help us remember him.</p></div>${gallery([26,25,30],'documents')}<div class="inscription">“May his soul rest in peace.”<p style="font:11px var(--sans);margin-top:14px;color:var(--muted)">The inscription recorded for his headstone, with his mother’s name beneath the entry.</p></div></section>
<section class="section full-bleed"><div class="wrap two-col wide-text"><div class="prose"><span class="eyebrow">FAMILY AND COMMUNITY</span><h2>Henry Norwest’s family<br>after the war.</h2><p>The <em>Edmonton Journal</em> newspaper article talks about Henry Norwest’s descendants, the medals associated with him, and how his community remembers him in Fort Saskatchewan. It also includes an interview with his great-granddaughter, who talks about Henry Norwest.</p><div class="button-row"><button class="button primary" data-image="24">Read the newspaper feature</button></div></div>${figure(24,'contain')}</div></section>${next('reflections','What this history teaches us')}`}

function reflections(){return `${top('07','Personal reflections','Reflections about<br><em>the War.</em>','Here are my reflections on the war and the Battle of Vimy Ridge.')}
<section class="section wrap"><div class="reflection-layout"><article><div class="reflection-num">01</div><h2 class="reflection-question">What did the soldier investigation reveal about the human experience of war?</h2><div class="reflection-essay">${paras(content.reflection1)}</div><div class="reflection-evidence"><button data-image="34">Pre-war photograph</button><button data-record="1">Personal service records</button><a href="#vimy/conditions">Conditions at the front</a></div></article><hr class="divider" style="margin:55px 0"><article><div class="reflection-num">02</div><h2 class="reflection-question">Should the memory of this battle be one of celebration or somber remembrance?</h2><div class="reflection-essay">${paras(content.reflection2)}</div><div class="reflection-evidence"><a href="#vimy">The battle and its aftermath</a><a href="#remembrance">Norwest’s remembrance</a><a href="#sources">Research sources</a></div></article></div></section>${next('archive','Look closer at the evidence')}`}

let archiveCategory='All',archiveQuery='';
function archive(){const cats=['All','Portraits','Documents','Service','Battle','Conditions','Aftermath','Maps','Newspapers','Remembrance','Art & poetry'];return `${top('08','The complete archive','The Original<br><em>Documents.</em>','Browse the original photographs and documents, plus all 66 pages of the personnel record.')}
<div class="wrap"><section class="archive-document-feature"><div class="paper-stack" aria-hidden="true"><img src="assets/records/page-03.webp" alt="" loading="lazy"><img src="assets/records/page-37.webp" alt="" loading="lazy"></div><div class="copy"><span class="eyebrow">THE COMPLETE PERSONNEL FILE · 66 PAGES</span><h2>Open the original records.</h2><p>Attestation papers, service entries, medical forms, pay records, and final administration.</p><button class="button light" data-record="1">Enter the document viewer</button></div></section><div class="archive-tools"><div class="search-field"><label class="sr-only" for="archive-search">Search images and documents</label><input id="archive-search" type="search" placeholder="Search the collection…" value="${esc(archiveQuery)}"></div><span id="archive-count" class="archive-count" aria-live="polite"></span></div><div class="filter-row" role="group" aria-label="Filter collection">${cats.map(c=>`<button class="filter-chip" data-category="${esc(c)}" aria-pressed="${c===archiveCategory}">${c}</button>`).join('')}</div><div id="archive-grid" class="archive-grid"></div></div>${next('sources','The sources behind the story')}`}
function renderArchive(){const grid=$('#archive-grid');if(!grid)return;const q=archiveQuery.toLowerCase();const filtered=assets.filter(a=>a.i!==21&&(archiveCategory==='All'||a.category===archiveCategory)&&`${a.title} ${a.caption} ${a.suppliedName} ${a.category}`.toLowerCase().includes(q));$('#archive-count').textContent=archiveQuery||archiveCategory!=='All'?`${filtered.length} results`:'';grid.innerHTML=filtered.length?filtered.map(a=>`<article class="archive-card">${imageButton(a.i)}<span class="asset-tag">${a.i===37?'ADDED MAP':`ITEM ${String(a.i+1).padStart(2,'0')}`} · ${esc(a.category)}</span><h3>${esc(a.title)}</h3>${a.caption?`<p>${esc(a.caption)}</p>`:''}</article>`).join(''):'<div class="empty-state"><h3>No matching items.</h3><p>Try another word or choose “All” to browse the collection.</p></div>'}

const sources=[
['Canadian War Museum. “The Taking of Vimy Ridge, Easter Monday 1917.” <em>Canada and the First World War</em>.',A(2).source,'Accessed 4 Oct. 2026.','Artwork · secondary interpretation'],
['Canadian War Museum. “Military Medal.” <em>Medals Collection</em>.','https://www.warmuseum.ca/medals-collection/medals/26/','Accessed 8 Oct. 2026.','Example medal photograph'],
['Cook, Tim. “The Battle of Vimy Ridge, April 9 to 12, 1917.” <em>Canadian War Museum</em>.',sourceLinks.museum,'Accessed 29 Sept. 2026.','Battle context'],
['Foot, Richard. “Battle of Vimy Ridge.” <em>The Canadian Encyclopedia</em>, 20 July 2006.','https://thecanadianencyclopedia.ca/en/article/vimy-ridge','Accessed 28 Sept. 2026.','Battle context · supplied bibliography'],
['Library and Archives Canada. “Norwest, Henry / Louie, Henry (AKA).” <em>First World War Personnel Records</em>, regimental no. 435684.','https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?IdNumber=550938&app=pffww','Accessed 4 Oct. 2026.','Primary source · attestation and personnel file'],
['Mackintosh, Ewart Alan. “On Vimy Ridge.” <em>A Highland Regiment and Other Poems</em>, John Lane, 1917, p. 48. <em>Wikisource</em>.',sourceLinks.poem,'Accessed 4 Oct. 2026.','Poem · Scottish soldier’s perspective'],
['Stewart, Briar. “Métis Sniper Made His Mark for Canada at Vimy Ridge.” <em>CBC News</em>, 4 Apr. 2017.',sourceLinks.cbc,'Accessed 29 Sept. 2026.','Biography · supplied bibliography'],
['Story, Eric. “Henry Norwest.” <em>The Canadian Encyclopedia</em>, 15 Mar. 2019.',sourceLinks.bio,'Accessed 28 Sept. 2026.','Biography · supplied bibliography'],
['Veterans Affairs Canada. “Battle of Vimy Ridge.” <em>Government of Canada</em>, 30 Mar. 2026.',sourceLinks.vimy,'Accessed 29 Sept. 2026.','Battle history and Canadian remembrance'],
['Veterans Affairs Canada. “Private Henry Louis Norwest.” <em>Canadian Virtual War Memorial</em>, Government of Canada, 19 Aug. 2026.',sourceLinks.vac,'Accessed 4 Oct. 2026.','Biographical details, commemoration, and image gallery'],
['Canadian War Museum. “Art and Culture – Official Art.” <em>Canada and the First World War</em>, 20 June 2008.','https://www.warmuseum.ca/firstworldwar/objects-and-photos/art-and-culture/official-art/?target=1893','Accessed 29 Sept. 2026.','Original supplied artwork reference']
];
function sourcePage(){const sorted=[...sources].sort((a,b)=>a[0].localeCompare(b[0]));return `${top('09','Works Cited','Works Cited.','The list of all the websites used to complete this project.')}
<section class="section wrap" id="bibliography"><div class="sources-list">${sorted.map(([t,u,d])=>`<article class="source-item"><p>${t} ${ext(u,esc(u))}. ${d}</p></article>`).join('')}</div></section>${next('home','Return to the beginning')}`}

const routes={home,life,service,timeline,vimy,poetry,remembrance,reflections,archive,sources:sourcePage};
let currentRoute='';
function navigate(){const hash=location.hash.slice(1)||'home';if(hash==='main'){$('#main').focus();return;}let [route,section]=hash.split('/');if(!routes[route])route='home';const changed=currentRoute!==route;if(changed){$('#main').innerHTML=`<div class="fade-in">${routes[route]()}</div>`;currentRoute=route;document.title=route==='home'?'The Life of Henry Norwest':`${({life:'His Life',service:'Military Service',timeline:'Interactive Timeline',vimy:'The Battle of Vimy Ridge',poetry:'Art & Poetry',remembrance:'Remembrance',reflections:'Personal Reflections',archive:'The Complete Archive',sources:'Works Cited'})[route]} — Henry Norwest`;document.querySelectorAll('#site-nav a').forEach(a=>{if(a.getAttribute('href')===`#${route}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(route==='archive')renderArchive();if(route==='timeline')requestAnimationFrame(prepareEventMedia);window.scrollTo({top:0,behavior:'instant'});}$('#site-nav').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');if(section){requestAnimationFrame(()=>document.getElementById(section)?.scrollIntoView({behavior:'smooth',block:'start'}));}else if(changed&&location.hash){$('#main').focus({preventScroll:true})}}
window.addEventListener('hashchange',navigate);
$('#menu-toggle').addEventListener('click',()=>{const open=$('#site-nav').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));});

const imageSequence=assets.filter(a=>a.i!==21).map(a=>a.i);
let imageIndex=0,imageZoom=1,imageRevealed=false;
function openImage(i){imageIndex=i;imageZoom=1;imageRevealed=false;renderImage();if(!$('#image-dialog').open)$('#image-dialog').showModal();}
function stepImage(delta){const next=imageSequence[imageSequence.indexOf(imageIndex)+delta];if(next!=null)openImage(next)}
function renderImage(){const a=A(imageIndex),position=imageSequence.indexOf(imageIndex);$('#image-position').textContent=`THE COLLECTION · ${position+1} / ${imageSequence.length}`;$('#image-title').textContent=a.title;$('#image-caption').textContent=a.caption;$('#image-caption').hidden=!a.caption;$('#image-original').href=a.original;$('#image-zoom-label').textContent=`${Math.round(imageZoom*100)}%`;const stage=$('#image-stage');stage.classList.toggle('zoomed',imageZoom>1);const width=Math.min(a.width,Math.max(240,window.innerWidth*.78));stage.innerHTML=`<img src="${a.src}" alt="${esc(a.title)}" ${imageZoom>1?`style="width:${width*imageZoom}px"`:''}>`;$('#image-zoom-in').disabled=imageZoom>=4;$('#image-zoom-out').disabled=imageZoom<=1;$('#image-prev').disabled=position===0;$('#image-next').disabled=position===imageSequence.length-1;}
$('#image-prev').onclick=()=>stepImage(-1);$('#image-next').onclick=()=>stepImage(1);$('#image-zoom-in').onclick=()=>{imageZoom=Math.min(4,imageZoom+.5);renderImage()};$('#image-zoom-out').onclick=()=>{imageZoom=Math.max(1,imageZoom-.5);renderImage()};$('#image-reset').onclick=()=>{imageZoom=1;renderImage()};
const medicalPages=[29,30,31,59,60];
let recordPage=1,recordZoom=1,recordMode='full';
function recordPages(){return recordMode==='medical'?medicalPages:Array.from({length:66},(_,i)=>i+1)}
function openRecord(page=1,mode='full'){recordMode=mode;recordPage=mode==='medical'?medicalPages[0]:page;recordZoom=1;const pages=recordPages();$('#record-thumbs').innerHTML=pages.map(i=>`<button data-record-page="${i}" aria-label="View personnel-file page ${i}"><img src="assets/records/thumb-${String(i).padStart(2,'0')}.webp" alt="" loading="lazy">${String(i).padStart(2,'0')}</button>`).join('');$('#record-title').textContent=mode==='medical'?'Medical history and hospital records':'The service record';$('#record-eyebrow').textContent=mode==='medical'?'ORIGINAL DOCUMENTS · MEDICAL PAGES ONLY':'ORIGINAL DOCUMENTS · COMPLETE FILE';$('#record-total').textContent=mode==='medical'?`of ${pages.length} selected pages`:'of 66';$('#record-page').readOnly=mode==='medical';$('#record-jump').disabled=mode==='medical';$('#record-bottom-note').textContent=mode==='medical'?'Only the medical history and hospital-treatment pages are shown here.':'All pages retained, including blank reverse sides.';$('#record-download').hidden=mode==='medical';if(!$('#record-dialog').open)$('#record-dialog').showModal();renderRecord()}
function stepRecord(delta){const pages=recordPages();const next=pages[pages.indexOf(recordPage)+delta];if(next){recordPage=next;renderRecord()}}
function renderRecord(){const img=$('#record-image');img.src=`assets/records/page-${String(recordPage).padStart(2,'0')}.webp`;img.alt=`Henry Norwest personnel record, original page ${recordPage} of 66`;$('#record-page').value=recordMode==='medical'?medicalPages.indexOf(recordPage)+1:recordPage;$('#record-prev').disabled=recordPage===recordPages()[0];$('#record-next').disabled=recordPage===recordPages().at(-1);$('#record-zoom-out').disabled=recordZoom<=1;$('#record-zoom-in').disabled=recordZoom>=3;$('#record-stage').classList.toggle('zoomed',recordZoom>1);img.style.width=recordZoom>1?`${Math.min(850,window.innerWidth*.85)*recordZoom}px`:'';$('#record-stage').scrollTop=0;$('#record-stage').scrollLeft=0;document.querySelectorAll('[data-record-page]').forEach(b=>b.setAttribute('aria-current',String(+b.dataset.recordPage===recordPage)));}
$('#record-prev').onclick=()=>stepRecord(-1);$('#record-next').onclick=()=>stepRecord(1);$('#record-page').onchange=e=>{recordPage=Math.max(1,Math.min(66,parseInt(e.target.value)||1));renderRecord()};$('#record-jump').onchange=e=>{recordPage=+e.target.value;recordZoom=1;renderRecord()};$('#record-zoom-in').onclick=()=>{recordZoom=Math.min(3,recordZoom+.5);renderRecord()};$('#record-zoom-out').onclick=()=>{recordZoom=Math.max(1,recordZoom-.5);renderRecord()};
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;const d=button.dataset;if(d.image!=null){openImage(+d.image);return}if(d.eventMedia){$('#event-media-image').src=d.eventMedia;$('#event-media-image').alt=d.eventLabel;$('#event-media-title').textContent=d.eventLabel;$('#event-media-original').href=d.eventMedia;const dialog=$('#event-media-dialog'),img=$('#event-media-image'),stage=dialog.querySelector('.image-stage'),rotation=+d.eventRotation||0;stage.classList.toggle('rotated-modal',rotation!==0);img.dataset.rotation=String(rotation);img.removeAttribute('style');img.onload=()=>fitRotated(img,stage,rotation);dialog.showModal();if(img.complete)fitRotated(img,stage,rotation);return}if(d.recordMedical){openRecord(29,'medical');return}if(d.record!=null){openRecord(+d.record);return}if(d.recordPage!=null){recordPage=+d.recordPage;recordZoom=1;renderRecord();return}if(d.close){document.getElementById(d.close).close();return}if(d.year){year=d.year;const first=content.timeline.findIndex(x=>year==='All'||x.year===year);if(year!=='All'&&content.timeline[eventIndex].year!==year)eventIndex=first;document.querySelectorAll('[data-year]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.year===year)));document.querySelectorAll('[data-event]').forEach(b=>b.hidden=year!=='All'&&content.timeline[+b.dataset.event].year!==year);updateEvent();return}if(d.event!=null){eventIndex=+d.event;updateEvent();return}if(d.eventStep){const visible=content.timeline.map((x,i)=>i).filter(i=>year==='All'||content.timeline[i].year===year);const pos=visible.indexOf(eventIndex);const next=visible[pos+Number(d.eventStep)];if(next!=null){eventIndex=next;updateEvent()}return}if(d.compare){document.querySelectorAll('[data-compare]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#comparison').innerHTML=comparison(+d.compare);return}if(d.category){archiveCategory=d.category;document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderArchive();return}});
function updateEvent(){document.querySelectorAll('[data-event]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.event===eventIndex)));$('#event-detail').innerHTML=eventDetail();prepareEventMedia();const active=document.querySelector(`[data-event="${eventIndex}"]`);if(window.innerWidth<=650)active?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});}
window.addEventListener('resize',()=>{prepareEventMedia();const dialog=$('#event-media-dialog');if(dialog.open){const img=$('#event-media-image');fitRotated(img,dialog.querySelector('.image-stage'),+img.dataset.rotation||0)}});
document.addEventListener('input',e=>{if(e.target.id==='archive-search'){archiveQuery=e.target.value;renderArchive()}});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if($('#image-dialog').open){if(e.key==='ArrowRight'){e.preventDefault();stepImage(1)}if(e.key==='ArrowLeft'){e.preventDefault();stepImage(-1)}}else if($('#record-dialog').open){if(e.key==='ArrowRight'){e.preventDefault();stepRecord(1)}if(e.key==='ArrowLeft'){e.preventDefault();stepRecord(-1)}}});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
navigate();
