export const assets = [
  {
    "i": 0,
    "title": "Vimy today · the memorial landscape",
    "id": "1_waAoDRy5zwxdHd51XBKBvYcbG-23uGA",
    "width": 246,
    "height": 164,
    "original": "02-documents-and-originals/assets/originals/asset-00.jpg",
    "src": "assets/asset-00.webp",
    "thumb": "assets/asset-00-thumb.webp",
    "category": "Remembrance",
    "caption": "An aerial view of the memorial within today’s preserved landscape.",
    "suppliedName": "Present battlefield - Vimy Ridge - 2",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 1,
    "title": "Vimy today · preserved battlefield",
    "id": "1gqXtU2GqHqIL07biHWRXOYmgGXc8T1P6",
    "width": 225,
    "height": 225,
    "original": "02-documents-and-originals/assets/originals/asset-01.jpg",
    "src": "assets/asset-01.webp",
    "thumb": "assets/asset-01-thumb.webp",
    "category": "Remembrance",
    "caption": "A present-day aerial view of the Vimy battlefield and memorial grounds.",
    "suppliedName": "Present battlefield - Vimy Ridge - 1",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 2,
    "title": "The Taking of Vimy Ridge, Easter Monday 1917",
    "id": "1xpK4_NOqG2bUYlzDVy0oIxo88tfv2eUz",
    "width": 2791,
    "height": 1696,
    "original": "02-documents-and-originals/assets/originals/asset-02.jpg",
    "src": "assets/asset-02.webp",
    "thumb": "assets/asset-02-thumb.webp",
    "category": "Art & poetry",
    "caption": "Richard Jack’s painting places a gun crew and wounded soldiers at the centre of the battle.",
    "suppliedName": "Artwork - Vimy Ridge",
    "credit": "Richard Jack. Beaverbrook Collection of War Art, Canadian War Museum, CWM 19710261-0160.",
    "source": "https://www.warmuseum.ca/firstworldwar/objects-and-photos/art-and-culture/official-art/the-taking-of-vimy-ridge-easter-monday-1917/",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 3,
    "title": "Living in the trenches",
    "id": "1cnUQgNo1WYkeDQuF-IpkeR5_ap88p1Dw",
    "width": 750,
    "height": 572,
    "original": "02-documents-and-originals/assets/originals/asset-03.jpg",
    "src": "assets/asset-03.webp",
    "thumb": "assets/asset-03-thumb.webp",
    "category": "Conditions",
    "caption": "Soldiers sitting in a narrow, muddy trench.",
    "suppliedName": "Vimy Ridge life 4",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 4,
    "title": "Burial behind the lines",
    "id": "1ozY0rC4AwJoL_3irL8fAV5kTg80GYH2s",
    "width": 750,
    "height": 516,
    "original": "02-documents-and-originals/assets/originals/asset-04.jpg",
    "src": "assets/asset-04.webp",
    "thumb": "assets/asset-04-thumb.webp",
    "category": "Conditions",
    "caption": "Soldiers carrying out a burial behind the lines.",
    "suppliedName": "Vimy Ridge life 4",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 5,
    "title": "Wading through the mud",
    "id": "1m-cIncSKlgf9Xcqx1cmBFuu4T7dM-Pbn",
    "width": 750,
    "height": 515,
    "original": "02-documents-and-originals/assets/originals/asset-05.jpg",
    "src": "assets/asset-05.webp",
    "thumb": "assets/asset-05-thumb.webp",
    "category": "Conditions",
    "caption": "Soldiers make their way through a flooded road.",
    "suppliedName": "Vimy Ridge life 3",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 6,
    "title": "A flooded tent",
    "id": "13_n4HxpTwJ4EGmIOHVJfpgCTP5UPYu-b",
    "width": 750,
    "height": 582,
    "original": "02-documents-and-originals/assets/originals/asset-06.jpg",
    "src": "assets/asset-06.webp",
    "thumb": "assets/asset-06-thumb.webp",
    "category": "Conditions",
    "caption": "A soldier beside a tent surrounded by water.",
    "suppliedName": "Vimy Ridge life 2",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 7,
    "title": "Camp and graves near Vimy",
    "id": "1c6r0UoEM17X4puMnRqgDhARlyHbXsCDA",
    "width": 750,
    "height": 517,
    "original": "02-documents-and-originals/assets/originals/asset-07.jpg",
    "src": "assets/asset-07.webp",
    "thumb": "assets/asset-07-thumb.webp",
    "category": "Conditions",
    "caption": "A military camp stands beside rows of graves.",
    "suppliedName": "Vimy Ridge life 1",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 8,
    "title": "Vimy village · after the destruction, view 2",
    "id": "1lKZwsJwDL8Gak7SmKHZOHKeaxdrFfBWV",
    "width": 750,
    "height": 459,
    "original": "02-documents-and-originals/assets/originals/asset-08.jpg",
    "src": "assets/asset-08.webp",
    "thumb": "assets/asset-08-thumb.webp",
    "category": "Aftermath",
    "caption": "Ruined buildings and the devastated village landscape.",
    "suppliedName": "Vimy Ridge after2",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 9,
    "title": "Vimy village · before the war, view 2",
    "id": "1k6zgBwY5P-mQh5C6axGiTfHiVQTTFHPW",
    "width": 750,
    "height": 460,
    "original": "02-documents-and-originals/assets/originals/asset-09.jpg",
    "src": "assets/asset-09.webp",
    "thumb": "assets/asset-09-thumb.webp",
    "category": "Aftermath",
    "caption": "A view of the village before wartime destruction.",
    "suppliedName": "Vimy Ridge before2",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 10,
    "title": "Vimy village · after the destruction, view 1",
    "id": "1YP8z-8O5LIkdbLb0xZB8v2XD4TI3ZJUK",
    "width": 750,
    "height": 490,
    "original": "02-documents-and-originals/assets/originals/asset-10.jpg",
    "src": "assets/asset-10.webp",
    "thumb": "assets/asset-10-thumb.webp",
    "category": "Aftermath",
    "caption": "A street lined with damaged buildings.",
    "suppliedName": "Vimy Ridge after1",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 11,
    "title": "The cost of battle",
    "id": "1VkXqXHwJAgTQ_doUM7zvMfg49NzkU_k9",
    "width": 750,
    "height": 468,
    "original": "02-documents-and-originals/assets/originals/asset-11.jpg",
    "src": "assets/asset-11.webp",
    "thumb": "assets/asset-11-thumb.webp",
    "category": "Aftermath",
    "caption": "Historical photograph showing dead soldiers on the battlefield.",
    "suppliedName": "Vimy Ridge Aftermath 2.jpg",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 12,
    "title": "A landscape changed by war",
    "id": "1bzjgmjrvV--ncJh6l85KcXUA4ROt174L",
    "width": 750,
    "height": 550,
    "original": "02-documents-and-originals/assets/originals/asset-12.jpg",
    "src": "assets/asset-12.webp",
    "thumb": "assets/asset-12-thumb.webp",
    "category": "Aftermath",
    "caption": "Shattered trees and water-filled ground in a devastated landscape.",
    "suppliedName": "Vimy Ridge aftermath 1.jpg",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 13,
    "title": "Vimy village · before the war, view 1",
    "id": "1wfJ6GbIiH6llZMx_aMhZ3NsxhJ3PfSWC",
    "width": 750,
    "height": 474,
    "original": "02-documents-and-originals/assets/originals/asset-13.jpg",
    "src": "assets/asset-13.webp",
    "thumb": "assets/asset-13-thumb.webp",
    "category": "Aftermath",
    "caption": "A street scene in Vimy before its destruction.",
    "suppliedName": "Vimy Ridge before1",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 14,
    "title": "Canadian Cemetery No. 2",
    "id": "19n6tl9biUo8i5pBLJchZ6nQ8XmLc-Ucv",
    "width": 246,
    "height": 164,
    "original": "02-documents-and-originals/assets/originals/asset-14.jpg",
    "src": "assets/asset-14.webp",
    "thumb": "assets/asset-14-thumb.webp",
    "category": "Remembrance",
    "caption": "The present-day photograph of Canadian Cemetery No. 2, near Vimy Ridge.",
    "suppliedName": "Cemetry of Vimy Ridge",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 15,
    "title": "Canadian National Vimy Memorial",
    "id": "1YhOkVbySQz4dVNS1r9ZDiWU_YvCusbqY",
    "width": 246,
    "height": 185,
    "original": "02-documents-and-originals/assets/originals/asset-15.jpg",
    "src": "assets/asset-15.webp",
    "thumb": "assets/asset-15-thumb.webp",
    "category": "Remembrance",
    "caption": "The memorial’s twin pylons rise above the preserved battlefield.",
    "suppliedName": "Monument of Vimy Ridge",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 16,
    "title": "The wider Western Front",
    "id": "1-ho05ctujf6NgHh7lhtj1XWdBSI7RuET",
    "width": 400,
    "height": 350,
    "original": "02-documents-and-originals/assets/originals/asset-16.png",
    "src": "assets/asset-16.webp",
    "thumb": "assets/asset-16-thumb.webp",
    "category": "Maps",
    "caption": "A regional map locating Vimy Ridge among other battles involving Canadians.",
    "suppliedName": "Map of Vimy RIdge",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 17,
    "title": "Soldiers moving through the battlefield",
    "id": "1TiWo-wAkqkbDgRfjA3lXUfVaWYlbfLMe",
    "width": 246,
    "height": 98,
    "original": "02-documents-and-originals/assets/originals/asset-17.jpg",
    "src": "assets/asset-17.webp",
    "thumb": "assets/asset-17-thumb.webp",
    "category": "Battle",
    "caption": "Historical battlefield photograph. Exact date and archival reference remain to be confirmed.",
    "suppliedName": "Vimy Ridge Pic 1",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 18,
    "title": "Troops along a trench",
    "id": "1MvGO4RCgotTVL-6zVPy_30P4nTYmVhKn",
    "width": 246,
    "height": 174,
    "original": "02-documents-and-originals/assets/originals/asset-18.jpg",
    "src": "assets/asset-18.webp",
    "thumb": "assets/asset-18-thumb.webp",
    "category": "Battle",
    "caption": "",
    "suppliedName": "Vimy Ridge Pic 5",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 19,
    "title": "Soldiers in a trench",
    "id": "1A7P9QCxuLyWzKe25gqKqfQ5l1jA8AFzv",
    "width": 197,
    "height": 255,
    "original": "02-documents-and-originals/assets/originals/asset-19.jpg",
    "src": "assets/asset-19.webp",
    "thumb": "assets/asset-19-thumb.webp",
    "category": "Battle",
    "caption": "A close view of soldiers and the confined conditions of trench warfare.",
    "suppliedName": "Vimy Ridge Pic 4",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 20,
    "title": "Across the ruined ground",
    "id": "1GhrxlW5hxuEb-vbSk9sF9QDvKwG98bQN",
    "width": 246,
    "height": 196,
    "original": "02-documents-and-originals/assets/originals/asset-20.jpg",
    "src": "assets/asset-20.webp",
    "thumb": "assets/asset-20-thumb.webp",
    "category": "Battle",
    "caption": "A view across a damaged battlefield landscape.",
    "suppliedName": "Vimy Ridge Pic 3",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 21,
    "title": "Vimy Ridge painting · supplied second copy",
    "id": "1OPt-juvoVuaDlJLOa8-itvTq22XZHymT",
    "width": 246,
    "height": 138,
    "original": "02-documents-and-originals/assets/originals/asset-21.jpg",
    "src": "assets/asset-21.webp",
    "thumb": "assets/asset-21-thumb.webp",
    "category": "Art & poetry",
    "caption": "A second, smaller copy of Richard Jack’s painting, retained from the original collection. This is artwork, not a photograph.",
    "suppliedName": "Vimy Ridge Pic 2",
    "credit": "Richard Jack. Beaverbrook Collection of War Art, Canadian War Museum, CWM 19710261-0160.",
    "source": "https://www.warmuseum.ca/firstworldwar/objects-and-photos/art-and-culture/official-art/the-taking-of-vimy-ridge-easter-monday-1917/",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 22,
    "title": "The Morning Bulletin · Vimy in the news",
    "id": "1_PgYgTCQnSrm3IEeFcL74rDBvgE8KFy9",
    "width": 860,
    "height": 1176,
    "original": "02-documents-and-originals/assets/originals/asset-22.jpg",
    "src": "assets/asset-22.webp",
    "thumb": "assets/asset-22-thumb.webp",
    "category": "Newspapers",
    "caption": "A wartime newspaper front page reports the capture of Vimy Ridge.",
    "suppliedName": "Newspaper 2 - Vimy Ridge",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 23,
    "title": "The Vancouver Daily Sun · Vimy in the news",
    "id": "1AkhlaMmrgGQIsvTLylIEjXpHT_VGyeW1",
    "width": 860,
    "height": 1164,
    "original": "02-documents-and-originals/assets/originals/asset-23.jpg",
    "src": "assets/asset-23.webp",
    "thumb": "assets/asset-23-thumb.webp",
    "category": "Newspapers",
    "caption": "A wartime front page reports the Canadian advance and the capture of Vimy Ridge.",
    "suppliedName": "Newspaper 1 - Vimy Ridge ",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 24,
    "title": "Remembered by his family and community",
    "id": "1mrgCxFapkmFDGfOFOQXXIxXKCcBT6R6h",
    "width": 1829,
    "height": 5596,
    "original": "02-documents-and-originals/assets/originals/asset-24.jpg",
    "src": "assets/asset-24.webp",
    "thumb": "assets/asset-24-thumb.webp",
    "category": "Newspapers",
    "caption": "Sheila Pratt’s Edmonton Journal feature includes family memories and photographs of Norwest’s descendants and commemoration.",
    "suppliedName": "Newspaper Article",
    "credit": "Sheila Pratt, Edmonton Journal. Photographs: Larry Wong. Publication date/page to be confirmed.",
    "source": "",
    "creditStatus": "partial",
    "sensitive": false
  },
  {
    "i": 25,
    "title": "The headstone inscription record",
    "id": "1P7XmaA5zoaC-8G3b5hOmoQPOmhfYkU9Q",
    "width": 659,
    "height": 815,
    "original": "02-documents-and-originals/assets/originals/asset-25.png",
    "src": "assets/asset-25.webp",
    "thumb": "assets/asset-25-thumb.webp",
    "category": "Documents",
    "caption": "The highlighted entry records “MAY HIS SOUL REST IN PEACE,” with Mrs. G. Norwest named beneath it.",
    "suppliedName": "Headstone Message Doc",
    "credit": "Imperial War Graves Commission / Commonwealth War Graves Commission. Exact archive link to be completed.",
    "source": "",
    "creditStatus": "partial",
    "sensitive": false
  },
  {
    "i": 26,
    "title": "Grave registration record",
    "id": "1bvo0T8erMHStt1iOFl_WfTxm8fpLDcvy",
    "width": 510,
    "height": 667,
    "original": "02-documents-and-originals/assets/originals/asset-26.png",
    "src": "assets/asset-26.webp",
    "thumb": "assets/asset-26-thumb.webp",
    "category": "Documents",
    "caption": "The highlighted entry identifies Norwest’s grave in Warvillers Churchyard Extension.",
    "suppliedName": "Grave Registration Doc",
    "credit": "Imperial War Graves Commission / Commonwealth War Graves Commission. Exact archive link to be completed.",
    "source": "",
    "creditStatus": "partial",
    "sensitive": false
  },
  {
    "i": 27,
    "title": "50th Battalion war diary",
    "id": "1jpRQigYOsCkbADl3rZkz7-WorHPMjMoC",
    "width": 915,
    "height": 575,
    "original": "02-documents-and-originals/assets/originals/asset-27.png",
    "src": "assets/asset-27.webp",
    "thumb": "assets/asset-27-thumb.webp",
    "category": "Documents",
    "caption": "A battalion diary entry describes Norwest’s patience and methods as a sniper. It is about him, not written by him.",
    "suppliedName": "War Diary",
    "credit": "50th Canadian Infantry Battalion. Exact archive reference to be completed.",
    "source": "",
    "creditStatus": "partial",
    "sensitive": false
  },
  {
    "i": 28,
    "title": "50th Battalion nominal roll",
    "id": "1du_WpSu0_yKpe_UHGI_WQXYhHwKDmQ4x",
    "width": 1176,
    "height": 670,
    "original": "02-documents-and-originals/assets/originals/asset-28.png",
    "src": "assets/asset-28.webp",
    "thumb": "assets/asset-28-thumb.webp",
    "category": "Documents",
    "caption": "The highlighted row records Henry Norwest, service number 435684, and his enlistment on 8 September 1915.",
    "suppliedName": "50th Battalion Nominal Roll",
    "credit": "50th Canadian Infantry Battalion. Exact archive reference to be completed.",
    "source": "",
    "creditStatus": "partial",
    "sensitive": false
  },
  {
    "i": 29,
    "title": "Norwest’s Ross rifle",
    "id": "1gMqsRk0q5x9yQXbIwm6pTnqD7wGFDZhf",
    "width": 246,
    "height": 138,
    "original": "02-documents-and-originals/assets/originals/asset-29.jpg",
    "src": "assets/asset-29.webp",
    "thumb": "assets/asset-29-thumb.webp",
    "category": "Service",
    "caption": "A Ross rifle associated with Henry Norwest.",
    "suppliedName": "Henry Norwest's Ross Rifle ",
    "credit": "Source credit to be completed",
    "source": "",
    "creditStatus": "pending",
    "sensitive": false
  },
  {
    "i": 30,
    "title": "First World War Book of Remembrance",
    "id": "1EyYIdvDmh_f2D_heCi5KGOiXIfD7y-5D",
    "width": 541,
    "height": 692,
    "original": "02-documents-and-originals/assets/originals/asset-30.jpg",
    "src": "assets/asset-30.webp",
    "thumb": "assets/asset-30-thumb.webp",
    "category": "Remembrance",
    "caption": "Norwest’s name appears on page 479 of Canada’s First World War Book of Remembrance.",
    "suppliedName": "WW1 Book of Remembrance",
    "credit": "Veterans Affairs Canada, Canadian Virtual War Memorial; individual image credit where recorded",
    "source": "https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 31,
    "title": "A tribute from his commanding officer",
    "id": "1T2GH0xO2phW3AejL1HKkZro6hLR1ltSN",
    "width": 600,
    "height": 989,
    "original": "02-documents-and-originals/assets/originals/asset-31.jpg",
    "src": "assets/asset-31.webp",
    "thumb": "assets/asset-31-thumb.webp",
    "category": "Documents",
    "caption": "A tribute dated 18 August 1918 remembers Norwest’s skill, patience, and loss to the 50th Battalion.",
    "suppliedName": "Tribute from Commander of the 50th Battalion",
    "credit": "Veterans Affairs Canada, Canadian Virtual War Memorial; individual image credit where recorded",
    "source": "https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 32,
    "title": "Norwest’s grave marker",
    "id": "1YmZX1OPvBt1SucaXv4Xdmi9Jz3H1Xpbs",
    "width": 600,
    "height": 969,
    "original": "02-documents-and-originals/assets/originals/asset-32.jpg",
    "src": "assets/asset-32.webp",
    "thumb": "assets/asset-32-thumb.webp",
    "category": "Remembrance",
    "caption": "The later headstone at Warvillers. Norwest’s own burial place is separate from the Vimy cemetery featured in the battle chapter.",
    "suppliedName": "Grave marker",
    "credit": "Veterans Affairs Canada, Canadian Virtual War Memorial; individual image credit where recorded",
    "source": "https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 33,
    "title": "The original grave marker",
    "id": "1vQVR3aMa6RcM7fv1zIvF2JyizBrgkLUc",
    "width": 535,
    "height": 408,
    "original": "02-documents-and-originals/assets/originals/asset-33.jpg",
    "src": "assets/asset-33.webp",
    "thumb": "assets/asset-33-thumb.webp",
    "category": "Remembrance",
    "caption": "The temporary marker erected by members of the 50th Battalion.",
    "suppliedName": "Original Grave Marker",
    "credit": "Veterans Affairs Canada, Canadian Virtual War Memorial; individual image credit where recorded",
    "source": "https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 34,
    "title": "Before the war · rodeo performer",
    "id": "10juDvYh1FeSO4R_xA6B1gZSk9nRAke5T",
    "width": 219,
    "height": 144,
    "original": "02-documents-and-originals/assets/originals/asset-34.jpg",
    "src": "assets/asset-34.webp",
    "thumb": "assets/asset-34-thumb.webp",
    "category": "Portraits",
    "caption": "Henry Norwest as a rodeo performer before the First World War.",
    "suppliedName": "Henry Prior to War",
    "credit": "Veterans Affairs Canada, Canadian Virtual War Memorial; individual image credit where recorded",
    "source": "https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 35,
    "title": "Henry Norwest · 1915",
    "id": "1geNnRMOc63mFagYBMm_1EtRp8q_pCje8",
    "width": 197,
    "height": 256,
    "original": "02-documents-and-originals/assets/originals/asset-35.jpg",
    "src": "assets/asset-35.webp",
    "thumb": "assets/asset-35-thumb.webp",
    "category": "Portraits",
    "caption": "Norwest photographed while a member of the 3rd Canadian Mounted Rifles in 1915.",
    "suppliedName": "Picture of Henry Norwest",
    "credit": "Veterans Affairs Canada, Canadian Virtual War Memorial; individual image credit where recorded",
    "source": "https://www.veterans.gc.ca/en/remembrance/memorials/canadian-virtual-war-memorial/585020",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 36,
    "title": "Attestation paper · 8 September 1915",
    "id": "1hBiyq4SqBNdjkGeVBPmduLzxVz9FbDaf",
    "width": 1012,
    "height": 1632,
    "original": "02-documents-and-originals/assets/originals/asset-36.gif",
    "src": "assets/asset-36.webp",
    "thumb": "assets/asset-36-thumb.webp",
    "category": "Documents",
    "caption": "Norwest’s enlistment paper records his name, family details, occupation, and signature.",
    "suppliedName": "Attestation Paper",
    "credit": "Library and Archives Canada, First World War personnel record, Henry Norwest / Henry Louie, regimental no. 435684.",
    "source": "https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?IdNumber=550938&app=pffww",
    "creditStatus": "verified",
    "sensitive": false
  },
  {
    "i": 37,
    "title": "The Battle of Vimy Ridge, 9–12 April 1917",
    "category": "Maps",
    "caption": "",
    "suppliedName": "Battle of Vimy Ridge map",
    "credit": "",
    "source": "",
    "creditStatus": "partial",
    "sensitive": false,
    "src": "assets/vimy-battle-map.jpg",
    "thumb": "assets/vimy-battle-map.jpg",
    "original": "assets/vimy-battle-map.jpg",
    "width": 792,
    "height": 506
  }
];
